fightland/djangobb_forum/urls.py
from django.conf.urls.defaults import *

from djangobb_forum import settings as forum_settings
from djangobb_forum import views as forum_views
from djangobb_forum.feeds import LastPosts, LastTopics, LastPostsOnForum,\
     LastPostsOnCategory, LastPostsOnTopic
from djangobb_forum.forms import EssentialsProfileForm,\
    PersonalProfileForm, MessagingProfileForm, PersonalityProfileForm,\
    DisplayProfileForm, PrivacyProfileForm, UploadAvatarForm
     

urlpatterns = patterns('',

    # Forum
    url('^$', forum_views.index, name='index'),
    url('^(?P<forum_id>\d+)/$', forum_views.show_forum, name='forum'),
    url('^moderate/(?P<forum_id>\d+)/$', forum_views.moderate, name='moderate'),
    url('^search/$', forum_views.search, name='search'),
    url('^misc/$', forum_views.misc, name='misc'),

    # User
    url('^user/(?P<username>.*)/upload_avatar/$', forum_views.upload_avatar, {
        'form_class': UploadAvatarForm,
        'template': 'djangobb_forum/upload_avatar.html'
        }, name='forum_profile_upload_avatar'),
    url('^user/(?P<username>.*)/privacy/$', forum_views.user, {
        'section': 'privacy',
        'form_class': PrivacyProfileForm,
        'template': 'djangobb_forum/profile/profile_privacy.html'
        }, name='forum_profile_privacy'),
    url('^user/(?P<username>.*)/display/$', forum_views.user, {
        'section': 'display',
        'form_class': DisplayProfileForm,
        'template': 'djangobb_forum/profile/profile_display.html'
        }, name='forum_profile_display'),
    url('^user/(?P<username>.*)/personality/$', forum_views.user, {
        'section': 'personality',
        'form_class': PersonalityProfileForm,
        'template': 'djangobb_forum/profile/profile_personality.html'
        }, name='forum_profile_personality'),
    url('^user/(?P<username>.*)/messaging/$', forum_views.user, {
        'section': 'messaging',
        'form_class': MessagingProfileForm,
        'template': 'djangobb_forum/profile/profile_messaging.html'
        }, name='forum_profile_messaging'),
    url('^user/(?P<username>.*)/personal/$', forum_views.user, {
        'section': 'personal',
        'form_class': PersonalProfileForm,
        'template': 'djangobb_forum/profile/profile_personal.html'
        }, name='forum_profile_personal'),
    url('^user/(?P<username>.*)/essentials/$', forum_views.user, name='forum_profile_essentials'),
    url('^user/(?P<username>.*)/$', forum_views.user, name='forum_profile'),
    url('^users/$', forum_views.users, name='forum_users'),

    # Topic
    url('^topic/(?P<topic_id>\d+)/$', forum_views.show_topic, name='topic'),
    url('^(?P<forum_id>\d+)/topic/add/$', forum_views.add_post,
        {'topic_id': None}, name='add_topic'),
    url('^topic/(?P<topic_id>\d+)/delete_posts/$', forum_views.delete_posts, name='delete_posts'),
    url('^topic/move/$', forum_views.move_topic, name='move_topic'),
    url('^topic/(?P<topic_id>\d+)/stick_unstick/(?P<action>[s|u])/$', forum_views.stick_unstick_topic, name='stick_unstick_topic'),
    url('^topic/(?P<topic_id>\d+)/open_close/(?P<action>[c|o])/$', forum_views.open_close_topic, name='open_close_topic'),

    # Post
    url('^topic/(?P<topic_id>\d+)/post/add/$', forum_views.add_post,
        {'forum_id': None}, name='add_post'),
    url('^post/(?P<post_id>\d+)/$', forum_views.show_post, name='post'),
    url('^post/(?P<post_id>\d+)/edit/$', forum_views.edit_post, name='edit_post'),
    url('^post/(?P<post_id>\d+)/delete/$', forum_views.delete_post, name='delete_post'),
    # Post preview
    url(r'^preview/$', forum_views.post_preview, name='post_preview'),

    # Subscription
    url('^subscription/topic/(?P<topic_id>\d+)/delete/$', forum_views.delete_subscription, name='forum_delete_subscription'),
    url('^subscription/topic/(?P<topic_id>\d+)/add/$', forum_views.add_subscription, name='forum_add_subscription'),
    
    # Feeds
    url(r'^feeds/posts/$', LastPosts(), name='forum_posts_feed'),
    url(r'^feeds/topics/$', LastTopics(), name='forum_topics_feed'),
    url(r'^feeds/topic/(?P<topic_id>\d+)/$', LastPostsOnTopic(), name='forum_topic_feed'),
    url(r'^feeds/forum/(?P<forum_id>\d+)/$', LastPostsOnForum(), name='forum_forum_feed'),
    url(r'^feeds/category/(?P<category_id>\d+)/$', LastPostsOnCategory(), name='forum_category_feed'),
)

### EXTENSIONS ###

# LOFI Extension
if (forum_settings.LOFI_SUPPORT):
    urlpatterns += patterns('',
        url('^lofi/$', forum_views.index, {'full':False}, name='lofi_index'),
        url('^(?P<forum_id>\d+)/lofi/$', forum_views.show_forum, {'full':False}, name='lofi_forum'),
        url('^topic/(?P<topic_id>\d+)/lofi/$', forum_views.show_topic, {'full':False}, name='lofi_topic'),
    )

# REPUTATION Extension
if (forum_settings.REPUTATION_SUPPORT):
    urlpatterns += patterns('',
        url('^reputation/(?P<username>.*)/$', forum_views.reputation, name='reputation'),
    )

# ATTACHMENT Extension
if (forum_settings.ATTACHMENT_SUPPORT):
    urlpatterns += patterns('',
        url('^attachment/(?P<hash>\w+)/$', forum_views.show_attachment, name='forum_attachment'),
    )

fightland/easy_news/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls.defaults import *
from django.views.generic.date_based import *
from easy_news.models import News
import datetime

from easy_news import settings as news_settings
archive_index_dict = {
    'queryset': News.objects.filter(show=True),
    'date_field': 'date',
    'template_object_name': 'object_list',
}

archive_year_dict = {
    'queryset': News.objects.filter(show=True),
    'date_field': 'date',
    'make_object_list': True,
}

archive_month_dict = {
    'queryset': News.objects.filter(show=True),
    'date_field': 'date',
    'month_format': '%m',
}

object_detail_dict = {
    'queryset': News.objects.filter(show=True),
    'date_field': 'date',
    'month_format': '%m',
    'slug_field': 'slug',
}

urlpatterns = patterns('',
    url(r'^(?P<year>\d{4})-(?P<month>\d{2})-(?P<day>\d{2})-(?P<slug>[-\w]+)/$', 'django.views.generic.date_based.object_detail', object_detail_dict, name='news_detail'),
)

if news_settings.ENABLE_NEWS_LIST:
    urlpatterns += patterns('',
        url(r'^list/$', 'easy_news.views.news_list', name='news_list'),
    )

if news_settings.ENABLE_NEWS_ARCHIVE_INDEX:
    urlpatterns += patterns('',
        url(r'^$', 'django.views.generic.date_based.archive_index', archive_index_dict, name='news_archive_index'),
    )

if news_settings.ENABLE_NEWS_DATE_ARCHIVE:
    urlpatterns += patterns('',
        url(r'^archive/(?P<year>\d{4})/$', 'django.views.generic.date_based.archive_year', archive_year_dict, name='news_archive_year'),
        url(r'^archive/(?P<year>\d{4})-(?P<month>\d{2})/$', 'django.views.generic.date_based.archive_month', archive_month_dict, name='news_archive_month'),
        url(r'^archive/(?P<year>\d{4})-(?P<month>\d{2})-(?P<day>\d{2})/$', 'django.views.generic.date_based.archive_day', archive_month_dict, name='news_archive_day'),
    )

if news_settings.NEWS_TAGGING:
    from tagging.views import tagged_object_list
    urlpatterns += patterns('',
        url(r'^tag/(?P<tag>[^/]+)/$', tagged_object_list,
            dict(queryset_or_model=News.objects.filter(show=True), paginate_by=10, allow_empty=True), name='news_tag_detail'),
    )

fightland/fightland/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
from infoportal.views import *
admin.autodiscover()
import os

media = os.path.join(os.path.dirname(__file__), 'media')

from sitemap import SitemapForum, SitemapTopic
from forms import RegistrationFormUtfUsername
from djangobb_forum import settings as forum_settings

sitemaps = {
    'forum': SitemapForum,
    'topic': SitemapTopic,
}

urlpatterns = patterns('',
    (r'^', include('infoportal.urls')),
    (r'^news/', include('easy_news.urls')),
    (r'^gallery/', include('fightlandgallery.urls')),
    (r'^video/$', video_list),

    # static content
    (r'^media/(?P<path>.*)$', 'django.views.static.serve',
        {'document_root': media}),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),

    # Sitemap
    (r'^sitemap.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),

    # Apps
    (r'^forum/account/', include('django_authopenid.urls')),
    (r'^forum/', include('djangobb_forum.urls', namespace='djangobb')),
)

# PM Extension
if (forum_settings.PM_SUPPORT):
    urlpatterns += patterns('',
        (r'^forum/pm/', include('django_messages.urls')),
   )

if (settings.DEBUG):
    urlpatterns += patterns('',
        (r'^%s(?P<path>.*)$' % settings.MEDIA_URL.lstrip('/'),
            'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    )

fightland/django_authopenid/forms.py
# -*- coding: utf-8 -*-
# Copyright 2007, 2008,2009 by Benoît Chesneau <benoitc@e-engura.org>
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
import re

from django import forms
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.utils.translation import ugettext as _
from django.conf import settings
# needed for some linux distributions like debian
try:
    from openid.yadis import xri
except ImportError:
    from yadis import xri
    
from django_authopenid.models import UserAssociation


class OpenidSigninForm(forms.Form):
    """ signin form """
    openid_url = forms.CharField(max_length=255, 
            widget=forms.widgets.TextInput(attrs={'class': 'required openid'}),
            label=_("OpenID URL"))
    
    def clean_openid_url(self):
        """ test if openid is accepted """
        if 'openid_url' in self.cleaned_data:
            openid_url = self.cleaned_data['openid_url']
            if xri.identifierScheme(openid_url) == 'XRI' and getattr(
                settings, 'OPENID_DISALLOW_INAMES', False
                ):
                raise forms.ValidationError(_('i-names are not supported'))
            return self.cleaned_data['openid_url']

attrs_dict = { 'class': 'required login' }
username_re = re.compile(r'^\w+$')

class OpenidRegisterForm(forms.Form):
    """ openid signin form """
    username = forms.CharField(max_length=30, 
            widget=forms.widgets.TextInput(attrs=attrs_dict))
    email = forms.EmailField(widget=forms.TextInput(attrs=dict(attrs_dict, 
        maxlength=200)), label=_('Email address'))
    
    def __init__(self, *args, **kwargs):
        super(OpenidRegisterForm, self).__init__(*args, **kwargs)
        self.user = None
    
    def clean_username(self):
        """ test if username is valid and exist in database """
        if 'username' in self.cleaned_data:
            if not username_re.search(self.cleaned_data['username']):
                raise forms.ValidationError(_("Usernames can only contain \
                    letters, numbers and underscores"))
            try:
                user = User.objects.get(
                        username__exact = self.cleaned_data['username']
                )
            except User.DoesNotExist:
                return self.cleaned_data['username']
            except User.MultipleObjectsReturned:
                raise forms.ValidationError(u'There is already more than one \
                    account registered with that username. Please try \
                    another.')
            self.user = user
            raise forms.ValidationError(_("This username is already \
                taken. Please choose another."))
            
    def clean_email(self):
        """For security reason one unique email in database"""
        if 'email' in self.cleaned_data:
            try:
                user = User.objects.get(email = self.cleaned_data['email'])
            except User.DoesNotExist:
                return self.cleaned_data['email']
            except User.MultipleObjectsReturned:
                raise forms.ValidationError(u'There is already more than one \
                    account registered with that e-mail address. Please try \
                    another.')
            raise forms.ValidationError(_("This email is already \
                registered in our database. Please choose another."))

class AssociateOpenID(forms.Form):
    """ new openid association form """
    openid_url = forms.CharField(max_length=255, 
            widget=forms.widgets.TextInput(attrs={'class': 'required openid'}),
            label=_("OpenID URL"))

    def __init__(self, user, *args, **kwargs):
        super(AssociateOpenID, self).__init__(*args, **kwargs)
        self.user = user
            
    def clean_openid_url(self):
        """ test if openid is accepted """
        if 'openid_url' in self.cleaned_data:
            openid_url = self.cleaned_data['openid_url']
            if xri.identifierScheme(openid_url) == 'XRI' and getattr(
                settings, 'OPENID_DISALLOW_INAMES', False
                ):
                raise forms.ValidationError(_('i-names are not supported'))
                
            try:
                rel = UserAssociation.objects.get(openid_url__exact=openid_url)
            except UserAssociation.DoesNotExist:
                return self.cleaned_data['openid_url']
            
            if rel.user != self.user:
                raise forms.ValidationError(_("This openid is already \
                    registered in our database by another account. Please choose another."))
                    
            raise forms.ValidationError(_("You already associated this openid to your account."))

class OpenidDissociateForm(OpenidSigninForm):
    """ form used to dissociate an openid. """
    openid_url = forms.CharField(max_length=255, widget=forms.widgets.HiddenInput())

fightland/fightland/forms.py
import re
from registration.forms import RegistrationFormUniqueEmail


class RegistrationFormUtfUsername(RegistrationFormUniqueEmail):
    '''
    Allowed UTF8 logins with space
    '''
    def __init__(self, *args, **kwargs):
        super(RegistrationFormUtfUsername, self).__init__(*args, **kwargs)
        self.fields['username'].regex = re.compile(r"^[\w\s-]+$", re.UNICODE)

fightland/fightland/templates/authopenid/associate.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
{% if msg %}
	<div class="errors"><p>{{ msg }}</p></div>
{% endif %}

{% if form.errors %}
    <div class="errors"><p>Openid url : {{ form.openid_url.errors|join:', ' }}</p></div>
{% endif %}

<div class="login">

<form name="openid_form" id="openid_form" action="{% url user_associate %}" method="post">
    <input type="hidden" name="action" value="verify" />
    <input type="hidden" name="next" value="{{ next }}" />
	<fieldset>
		<legend>{% trans "Add a new OpenID URL" %}</legend>
		<div id="openid_choice">
    		<p>Please click your account provider:</p>
    		<div id="openid_btns"></div>
    	</div>
    	<div id="openid_input_area">
            <label for="id_openid_url">{% trans "OpenId URL :" %}</label><br />{{ form.openid_url }}
            <input name="openid_submit" type="submit" value="{% trans "Add OpenID" %}">
		</div>
	</fieldset>
</form>
</div>
{% endblock %}

{% block extra_scripts %}
<script type="text/javascript" src="{{ STATIC_URL }}openid/js/openid-jquery.js"></script>
<script type="text/javascript">
$(document).ready(function() {
    openid.init('id_openid_url');
});
</script>
{% endblock %}

fightland/fightland/templates/authopenid/complete.html
{% extends "djangobb_forum/base.html" %}
{% load i18n %}
{% load forum_extras %}

{% block content %}
<div class="blockform">
	<h2><span>{% trans "OpenID is verified" %}</span></h2>
	<div class="box">
			<div class="inform">
				<form name="fregister" action="{% url user_register %}" method="POST">
				{% csrf_token %}
				<div class="forminfo">
					<h3>{% trans "Your OpenID is verified! " %}</h3>
					{% blocktrans %}
					<p>Your OpenID can now be associated with a new or existing membership. You can change the association later in your preferences.</p>
					{% endblocktrans %}
				</div>
				<div class="forminfo">
					<h3>{% trans "Associate your OpenID" %}</h3>
					{% blocktrans %}
					<p>If you're joining <strong>Sitename</strong>, associate your OpenID with a new account. If you're already a member, associate with your existing account.</p>
					{% endblocktrans %}
				</div>
				<fieldset>
					<legend>{% trans "A new account" %}</legend>
						<div class="infldset">
							{{ form1.username.errors }}
							{{ form1.email.errors }}
							<label for="id_username1"><strong>{% trans "Username" %}</strong><br />{{ form1.username }}<br /></label>
							<label for="id_email1"><strong>{% trans "Email" %}</strong><br />{{ form1.email }}<br /></label>
							<p><input type="submit" value="{% trans "Create account" %}" /></p>
						</div>
				</fieldset>
				</form>
			</div>
			<div class="inform">
				<form name="fverify" action="{% url user_register %}" method="POST">
				{% csrf_token %}
				<fieldset>
					<legend>{% trans "An existing account" %}</legend>
						<div class="infldset">
							{{ form2.username.errors }}
							{{ form2.password.errors }}
							<label for="id_username2"><strong>{% trans "Username" %}</strong><br />{{ form2.username }}<br /></label>
							<label for="id_password2"><strong>{% trans "Password" %}</strong><br />{{ form2.password }}<br /></label>
							<p><input type="submit" value="{% trans "Verify" %}" /></p>
						</div>
				</fieldset>
				</form>
			</div>
	</div>
</div>
{% endblock %}

fightland/fightland/templates/authopenid/dissociate.html
{% extends "base.html" %}
{% load i18n %}

{% block head %}


{% endblock %}


{% block content %}
{% if msg %}
	<p class="warning">{{ msg }}</p>
{% endif %}

<div class="login">

<form name="fopenid" action="" method="post">
    <input type="hidden" name="next" value="{{ next }}" />
	{{ form.openid_url }}
	<fieldset>
		<legend>{% trans "Dissociate OpenID URL" %}</legend>
        <p>Confirm to dissociate {{ openid_url }} from your account</p>
        <div class="submit-row "><input name="bdissociate" type="submit" value="{% trans "Dissociate OpenID" %}"></div>
		
	</fieldset>
</form>	
</div>	
{% endblock %}

fightland/fightland/templates/authopenid/failure.html
{% extends "djangobb_forum/base.html" %}
{% load i18n %}
{% load forum_extras %}

{% block content %}
<div class="blockform">
	<h2><span>{% trans "Message" %}</span></h2>
	<div class="box">
			<div class="inform message">
				<div class="forminfo">
					<h3>{% trans "OpenID failed" %}</h3>
					<p>{{ message|escape }}</p>
				</div>
			</div>
	</div>
</div>
{% endblock %}

fightland/fightland/templates/authopenid/password_change_form.html
{% extends "djangobb_forum/base.html" %}
{% load i18n %}


{% block content %}




{% if set_password %}
<div class="blockform"> 
	<h2><span>{% trans 'Set password' %}</span></h2> 
	<div class="box"> 
		<form action="" method="post">
			{% csrf_token %}
			<div class="inform"> 
				<input type="hidden" name="form_sent" value="1" /> 
				<fieldset> 
					<legend>{% trans "Please enter your new password twice so we can verify you typed it in correctly." %}</legend> 
					<div class="infldset"> 
						<label class="conl"><strong>{% trans 'New password:' %}</strong><br /> 
						{{ form.new_password1 }}<br /></label> 
						<label class="conl"><strong>{% trans 'Confirm password:' %}</strong><br /> 
						{{ form.new_password2 }}<br /></label> 
						<div class="clearb"></div> 
					</div> 
				</fieldset> 
			</div> 
			<p><input type="submit" value="{% trans 'Change my password' %}" /><a href="javascript:history.go(-1)">{% trans 'Go back' %}</a></p> 
		</form> 
	</div> 
</div> 

{% else %}

<div class="blockform"> 
	<h2><span>{% trans 'Password change' %}</span></h2> 
	<div class="box"> 
		<form action="" method="post">
			{% csrf_token %}
			<div class="inform"> 
				<input type="hidden" name="form_sent" value="1" /> 
				<fieldset> 
					<legend>{% trans "Please enter your old password, for security's sake, and then enter your new password twice so we can verify you typed it in correctly." %}</legend> 
					<div class="infldset"> 
						<label><strong>{% trans 'Old password:' %}</strong><br /> 
						{{ form.old_password.errors }}
						{{ form.old_password }}<br /></label> 
						<label class="conl"><strong>{% trans 'New password:' %}</strong><br /> 
						{{ form.new_password1.errors }}
						{{ form.new_password1 }}<br /></label> 
						<label class="conl"><strong>{% trans 'Confirm password:' %}</strong><br /> 
						{{ form.new_password2.errors }}
						{{ form.new_password2 }}<br /></label> 
						<div class="clearb"></div> 
					</div> 
				</fieldset> 
			</div> 
			<p><input type="submit" value="{% trans 'Change my password' %}" /><a href="javascript:history.go(-1)">{% trans 'Go back' %}</a></p> 
		</form> 
	</div> 
</div> 

{% endif %}
{% endblock %} 

fightland/fightland/templates/authopenid/signin.html
{% extends "djangobb_forum/base.html" %}
{% load i18n %}
{% block extra_meta %}
<link rel="stylesheet" href="{{ STATIC_URL }}openid/css/openid-shadow.css" />
<script type="text/javascript" src="{{ STATIC_URL }}openid/js/openid-jquery.js"></script>
{% if LANGUAGE_CODE in 'de,en,jp,ru,uk' %}
	<script type="text/javascript" src="{{ STATIC_URL }}openid/js/openid-{{ LANGUAGE_CODE }}.js"></script>
{% else %}
	<script type="text/javascript" src="{{ STATIC_URL }}openid/js/openid-en.js"></script>
{% endif %}
<script type="text/javascript">
$(document).ready(function() {
    openid.init('openid_url');
});
</script>
{% endblock %}
{% block content %}
<div class="blockform">
    <h2><span>{% trans "Login" %}</span></h2>
    <div class="box">
		<form id="registration_form" action="." method="post">
		{% csrf_token %}
		<div class="inform">
			{% if msg %}
			<ul class="errorlist">
			    <li>{{ msg }}</li>
			</ul>
			{% endif %}
			{{ form1.non_field_errors.as_ul }}
			{{ form2.non_field_errors.as_ul }}
			<fieldset>
				<legend>{% trans "Sign in using your username and password" %}</legend>
					<div class="infldset">
						{{ form2.username.errors }}
						<label><strong>{{ form2.username.label }}</strong><br />{{ form2.username }}</label>
						{{ form2.password.errors }}
						<label><strong>{{ form2.password.label }}</strong><br />{{ form2.password }}</label>
						<p class="clearb">{% trans "If you have not registered or have forgotten your password click on the appropriate link below." %}</p>
						<p>
							<a href="{% url registration_register %}">{% trans "Not registered yet?" %}</a>&nbsp;&nbsp;
							<a href="{% url auth_password_reset %}">{% trans "Forgotten your password?" %}</a>
						</p>
					</div>
			</fieldset>
		</div>
		<p>
            <input type="hidden" name="next" value="{{ next }}" />
            <input type="submit" value="{% trans "Login" %}" />
        </p>
		</form>

		<form id="openid_form" name="openid_form" action="." method="post">
		{% csrf_token %}
		<fieldset>
        <input type="hidden" name="action" value="verify" />
        <input type="hidden" name="next" value="{{ next }}" />
		<legend>{% trans "Sign In Using Your OpenID URL" %}</legend>
			<div id="openid_choice">
				<p>{% trans "Please click your account provider:" %}</p>
				<div id="openid_btns"></div>
			</div>
		<div id="openid_input_area">
		    {{ form1.openid_url.errors }}
		    <label for="id_openid_url">OpenId URL :</label>{{ form1.openid_url }}
		    <input name="openid_submit" type="submit" value="{% trans "Sign in with OpenID" %}" />
		</div>
		</fieldset>
		</form>
    </div>
</div>
{% endblock %}